import greenfoot.*;  // (World, Actor, GreenfootImage, Greenfoot and MouseInfo)

/**
 * Write a description of class Erdgeschoss1u2 here.
 * 
 * @author (your name) 
 * @version (a version number or a date)
 */
public class Erdgeschoss1u2 extends World
{
    private static int zellenGroesse = 50;
    /**
     * Constructor for objects of class Erdgeschoss1u2.
     * 
     */
    public Erdgeschoss1u2()   
    {    
        // Create a new world with 600x400 cells with a cell size of 1x1 pixels.

        super(21, 16, zellenGroesse);
        setBackground("images/Schuleboden.png");
        setPaintOrder(String.class, Rover.class, Marke.class, Gestein.class, Huegel.class);
        Greenfoot.setSpeed(35);

        prepare();
        this.addObject(new Gulli(), 10, 7);
        
    }
    
    /**
     * Prepare the world for the start of the program.
     * That is: create the initial objects and add them to the world.
     */
    private void prepare()
    {
        Background background = new Background();
        addObject(background,20,0);
        Background background2 = new Background();
        addObject(background2,20,1);
        Background background3 = new Background();
        addObject(background3,20,2);
        Background background4 = new Background();
        addObject(background4,20,8);
        Background background5 = new Background();
        addObject(background5,19,8);
        Background background6 = new Background();
        addObject(background6,18,8);
        Background background7 = new Background();
        addObject(background7,19,2);
        Background background8 = new Background();
        addObject(background8,18,2);
        Background background9 = new Background();
        addObject(background9,20,3);
        Background background10 = new Background();
        addObject(background10,19,3);
        Background background11 = new Background();
        addObject(background11,18,3);
        Background background12 = new Background();
        addObject(background12,17,3);
        Background background13 = new Background();
        addObject(background13,17,8);
        Background background14 = new Background();
        addObject(background14,16,8);
        Background background15 = new Background();
        addObject(background15,15,8);
        Background background16 = new Background();
        addObject(background16,4,0);
        Background background17 = new Background();
        addObject(background17,4,1);
        Background background18 = new Background();
        addObject(background18,4,2);
        Background background19 = new Background();
        addObject(background19,4,3);
        Background background20 = new Background();
        addObject(background20,4,4);
        Background background21 = new Background();
        addObject(background21,5,5);
        Background background22 = new Background();
        addObject(background22,4,5);
        Background background23 = new Background();
        addObject(background23,4,6);
        Background background24 = new Background();
        addObject(background24,4,7);
        Background background25 = new Background();
        addObject(background25,3,7);
        Background background26 = new Background();
        addObject(background26,2,7);
        Background background27 = new Background();
        addObject(background27,1,7);
        Background background28 = new Background();
        addObject(background28,0,7);
        Background background29 = new Background();
        addObject(background29,3,15);
        removeObject(background29);
        removeObject(background25);
        removeObject(background26);
        removeObject(background27);
        removeObject(background28);

        addObject(background29,2,10);
        Background background30 = new Background();
        addObject(background30,1,10);
        Background background31 = new Background();
        addObject(background31,0,10);
        Background background32 = new Background();
        addObject(background32,0,15);
        Background background33 = new Background();
        addObject(background33,1,15);
        Background background34 = new Background();
        addObject(background34,2,15);
        Background background35 = new Background();
        addObject(background35,3,15);
        Background background36 = new Background();
        addObject(background36,4,15);
        Background background37 = new Background();
        addObject(background37,5,15);
        Background background38 = new Background();
        addObject(background38,6,15);
        Background background39 = new Background();
        addObject(background39,7,15);
        Background background40 = new Background();
        addObject(background40,8,15);
        Background background41 = new Background();
        addObject(background41,9,15);
        Background background42 = new Background();
        addObject(background42,9,14);
        Background background43 = new Background();
        addObject(background43,9,13);
        Background background44 = new Background();
        addObject(background44,9,12);
        Background background45 = new Background();
        addObject(background45,9,11);
        Background background46 = new Background();
        addObject(background46,9,10);
        Background background47 = new Background();
        addObject(background47,10,10);
        Background background48 = new Background();
        addObject(background48,11,10);
        Background background49 = new Background();
        addObject(background49,12,10);
        Background background50 = new Background();
        addObject(background50,13,10);
        Background background51 = new Background();
        addObject(background51,14,10);
        Background background52 = new Background();
        addObject(background52,15,10);
        Background background53 = new Background();
        addObject(background53,16,10);
        Background background54 = new Background();
        addObject(background54,17,10);
        Background background55 = new Background();
        addObject(background55,18,10);
        Background background56 = new Background();
        addObject(background56,19,10);
        Background background57 = new Background();
        addObject(background57,20,10);
        removeObject(background4);
        removeObject(background5);
        removeObject(background6);
        removeObject(background13);
        removeObject(background14);
        removeObject(background15);
        removeObject(background21);

        addObject(background15,16,5);

        addObject(background21,15,5);
        Background background58 = new Background();
        addObject(background58,14,5);
        Background background59 = new Background();
        addObject(background59,13,5);
        Background background60 = new Background();
        addObject(background60,12,5);
        Background background61 = new Background();
        addObject(background61,11,5);
        Background background62 = new Background();
        addObject(background62,10,5);
        Background background63 = new Background();
        addObject(background63,9,5);
        Background background64 = new Background();
        addObject(background64,9,4);
        Background background65 = new Background();
        addObject(background65,9,3);
        Background background66 = new Background();
        addObject(background66,9,2);
        Background background67 = new Background();
        addObject(background67,9,1);
        Background background68 = new Background();
        addObject(background68,9,0);
        Background background69 = new Background();
        addObject(background69,19,11);
        Background background70 = new Background();
        addObject(background70,18,11);
        Background background71 = new Background();
        addObject(background71,17,11);
        Background background72 = new Background();
        addObject(background72,16,11);
        Background background73 = new Background();
        addObject(background73,15,11);
        Background background74 = new Background();
        addObject(background74,14,11);
        Background background75 = new Background();
        addObject(background75,13,11);
        Background background76 = new Background();
        addObject(background76,12,11);
        background76.setLocation(12,11);
        Background background77 = new Background();
        addObject(background77,12,11);
        Background background78 = new Background();
        addObject(background78,11,11);
        Background background79 = new Background();
        addObject(background79,10,11);
        Background background80 = new Background();
        addObject(background80,10,12);
        Background background81 = new Background();
        addObject(background81,11,12);
        Background background82 = new Background();
        addObject(background82,10,13);
        Background background83 = new Background();
        addObject(background83,10,14);
        Background background84 = new Background();
        addObject(background84,10,15);
        Background background85 = new Background();
        addObject(background85,11,13);
        Background background86 = new Background();
        addObject(background86,11,14);
        Background background87 = new Background();
        addObject(background87,11,15);
        Background background88 = new Background();
        addObject(background88,12,15);
        Background background89 = new Background();
        addObject(background89,20,11);
        Background background90 = new Background();
        addObject(background90,20,12);
        Background background91 = new Background();
        addObject(background91,20,13);
        Background background92 = new Background();
        addObject(background92,20,14);
        Background background93 = new Background();
        addObject(background93,20,15);
        Background background94 = new Background();
        addObject(background94,19,15);
        Background background95 = new Background();
        addObject(background95,18,15);
        Background background96 = new Background();
        addObject(background96,17,15);
        Background background97 = new Background();
        addObject(background97,17,15);
        Background background98 = new Background();
        addObject(background98,16,15);
        Background background99 = new Background();
        addObject(background99,15,15);
        Background background100 = new Background();
        addObject(background100,14,15);
        Background background101 = new Background();
        addObject(background101,13,15);
        Background background102 = new Background();
        addObject(background102,19,14);
        Background background103 = new Background();
        addObject(background103,19,13);
        Background background104 = new Background();
        addObject(background104,19,12);
        Background background105 = new Background();
        addObject(background105,18,14);
        WaendeHindernisse waendeHindernisse = new WaendeHindernisse();
        addObject(waendeHindernisse,18,13);
        removeObject(waendeHindernisse);
        Background background106 = new Background();
        addObject(background106,18,13);
        Background background107 = new Background();
        addObject(background107,18,12);
        Background background108 = new Background();
        addObject(background108,17,14);
        Background background109 = new Background();
        addObject(background109,17,13);
        Background background110 = new Background();
        addObject(background110,17,12);
        Background background111 = new Background();
        addObject(background111,16,12);
        Background background112 = new Background();
        addObject(background112,16,14);
        Background background113 = new Background();
        addObject(background113,16,13);
        Background background114 = new Background();
        addObject(background114,15,12);
        Background background115 = new Background();
        addObject(background115,15,13);
        Background background116 = new Background();
        addObject(background116,15,14);
        Background background117 = new Background();
        addObject(background117,14,14);
        Background background118 = new Background();
        addObject(background118,14,13);
        Background background119 = new Background();
        addObject(background119,14,12);
        Background background120 = new Background();
        addObject(background120,13,14);
        Background background121 = new Background();
        addObject(background121,12,14);
        Background background122 = new Background();
        addObject(background122,13,13);
        Background background123 = new Background();
        addObject(background123,13,12);
        Background background124 = new Background();
        addObject(background124,12,12);
        Background background125 = new Background();
        addObject(background125,12,13);
        Background background126 = new Background();
        addObject(background126,3,10);
        Background background127 = new Background();
        addObject(background127,4,10);
        Background background128 = new Background();
        addObject(background128,4,9);
        Background background129 = new Background();
        addObject(background129,4,8);
        Background background130 = new Background();
        addObject(background130,17,5);
        Background background131 = new Background();
        addObject(background131,18,5);
        Background background132 = new Background();
        addObject(background132,19,5);
        Background background133 = new Background();
        addObject(background133,20,5);
        Background background134 = new Background();
        addObject(background134,20,4);
        Background background135 = new Background();
        addObject(background135,19,4);
        Background background136 = new Background();
        addObject(background136,18,4);
        Background background137 = new Background();
        addObject(background137,17,4);
        Background background138 = new Background();
        addObject(background138,16,4);
        Background background139 = new Background();
        addObject(background139,19,1);
        Background background140 = new Background();
        addObject(background140,10,4);
        Background background141 = new Background();
        addObject(background141,11,4);
        Background background142 = new Background();
        addObject(background142,12,4);
        Background background143 = new Background();
        addObject(background143,10,3);
        Background background144 = new Background();
        addObject(background144,11,3);
        Background background145 = new Background();
        addObject(background145,10,2);
        Background background146 = new Background();
        addObject(background146,10,1);
        Background background147 = new Background();
        addObject(background147,10,0);
        Background background148 = new Background();
        addObject(background148,11,2);
        Background background149 = new Background();
        addObject(background149,12,3);
        Background background150 = new Background();
        addObject(background150,13,4);
        Background background151 = new Background();
        addObject(background151,14,4);
        Background background152 = new Background();
        addObject(background152,13,3);
        Background background153 = new Background();
        addObject(background153,12,2);
        Background background154 = new Background();
        addObject(background154,11,1);
        background138.setLocation(15,4);
        Background background155 = new Background();
        addObject(background155,15,4);
        Background background156 = new Background();
        addObject(background156,17,2);
        Background background157 = new Background();
        addObject(background157,13,2);
        Background background158 = new Background();
        addObject(background158,16,1);
        Background background159 = new Background();
        addObject(background159,17,1);
        Background background160 = new Background();
        addObject(background160,13,1);
        Background background161 = new Background();
        addObject(background161,14,1);
        Background background162 = new Background();
        addObject(background162,15,1);
        Background background163 = new Background();
        addObject(background163,18,1);
        Background background164 = new Background();
        addObject(background164,19,0);
        Background background165 = new Background();
        addObject(background165,18,0);
        Background background166 = new Background();
        addObject(background166,17,0);
        Background background167 = new Background();
        addObject(background167,16,0);
        Background background168 = new Background();
        addObject(background168,15,0);
        Background background169 = new Background();
        addObject(background169,14,0);
        Background background170 = new Background();
        addObject(background170,13,0);
        Background background171 = new Background();
        addObject(background171,12,0);
        Background background172 = new Background();
        addObject(background172,12,1);
        Background background173 = new Background();
        addObject(background173,11,0);
        Background background174 = new Background();
        addObject(background174,16,2);
        Background background175 = new Background();
        addObject(background175,16,3);
        Background background176 = new Background();
        addObject(background176,15,3);
        Background background177 = new Background();
        addObject(background177,15,2);
        Background background178 = new Background();
        addObject(background178,14,3);
        Background background179 = new Background();
        addObject(background179,14,2);
        Background background180 = new Background();
        addObject(background180,16,4);
        Background background181 = new Background();
        addObject(background181,3,9);
        Background background182 = new Background();
        addObject(background182,2,9);
        Background background183 = new Background();
        addObject(background183,1,9);
        Background background184 = new Background();
        addObject(background184,0,9);
        Background background185 = new Background();
        addObject(background185,0,8);
        Background background186 = new Background();
        addObject(background186,0,7);
        Background background187 = new Background();
        addObject(background187,0,6);
        Background background188 = new Background();
        addObject(background188,0,5);
        Background background189 = new Background();
        addObject(background189,0,4);
        Background background190 = new Background();
        addObject(background190,0,3);
        Background background191 = new Background();
        addObject(background191,0,2);
        Background background192 = new Background();
        addObject(background192,0,1);
        Background background193 = new Background();
        addObject(background193,0,0);
        Background background194 = new Background();
        addObject(background194,1,0);
        Background background195 = new Background();
        addObject(background195,2,0);
        background195.setLocation(2,0);
        Background background196 = new Background();
        addObject(background196,2,0);
        Background background197 = new Background();
        addObject(background197,3,0);
        Background background198 = new Background();
        addObject(background198,3,1);
        Background background199 = new Background();
        addObject(background199,3,2);
        Background background200 = new Background();
        addObject(background200,3,3);
        Background background201 = new Background();
        addObject(background201,2,1);
        Background background202 = new Background();
        addObject(background202,1,1);
        Background background203 = new Background();
        addObject(background203,1,2);
        Background background204 = new Background();
        addObject(background204,2,2);
        Background background205 = new Background();
        addObject(background205,1,3);
        Background background206 = new Background();
        addObject(background206,3,8);
        Background background207 = new Background();
        addObject(background207,1,8);
        Background background208 = new Background();
        addObject(background208,2,8);
        Background background209 = new Background();
        addObject(background209,3,7);
        Background background210 = new Background();
        addObject(background210,2,7);
        Background background211 = new Background();
        addObject(background211,1,7);
        background23.setLocation(4,6);
        Background background212 = new Background();
        addObject(background212,4,6);
        Background background213 = new Background();
        addObject(background213,3,6);
        Background background214 = new Background();
        addObject(background214,2,6);
        Background background215 = new Background();
        addObject(background215,1,6);
        Background background216 = new Background();
        addObject(background216,1,5);
        Background background217 = new Background();
        addObject(background217,3,5);
        Background background218 = new Background();
        addObject(background218,2,5);
        Background background219 = new Background();
        addObject(background219,3,4);
        Background background220 = new Background();
        addObject(background220,2,3);
        Background background221 = new Background();
        addObject(background221,1,4);
        Background background222 = new Background();
        addObject(background222,2,4);
        Dummy4 dummy4 = new Dummy4();
        addObject(dummy4,20,9);
        Dummy4 dummy42 = new Dummy4();
        addObject(dummy42,20,8);
        Dummy4 dummy43 = new Dummy4();
        addObject(dummy43,20,7);
        Dummy4 dummy44 = new Dummy4();
        addObject(dummy44,20,6);
        removeObject(background129);
        TreppeEzu210 treppeEzu210 = new TreppeEzu210();
        addObject(treppeEzu210,4,8);
        removeObject(background17);
        TreppeEzu110 treppeEzu110 = new TreppeEzu110();
        addObject(treppeEzu110,4,1);
    }
}

